import { PermissionCode } from '@/types/database';

// Permission constants organized by category
export const PERMISSIONS = {
  FIRM: {
    MANAGE: 'firm.manage' as PermissionCode,
    VIEW_SETTINGS: 'firm.view_settings' as PermissionCode,
  },
  TEAM: {
    INVITE: 'team.invite' as PermissionCode,
    REMOVE: 'team.remove' as PermissionCode,
    VIEW: 'team.view' as PermissionCode,
    CHANGE_ROLES: 'team.change_roles' as PermissionCode,
  },
  CASES: {
    VIEW_ALL: 'cases.view_all' as PermissionCode,
    VIEW_ASSIGNED: 'cases.view_assigned' as PermissionCode,
    CREATE: 'cases.create' as PermissionCode,
    EDIT: 'cases.edit' as PermissionCode,
    DELETE: 'cases.delete' as PermissionCode,
    ASSIGN: 'cases.assign' as PermissionCode,
  },
  CLIENTS: {
    VIEW_ALL: 'clients.view_all' as PermissionCode,
    VIEW_ASSIGNED: 'clients.view_assigned' as PermissionCode,
    CREATE: 'clients.create' as PermissionCode,
    EDIT: 'clients.edit' as PermissionCode,
    DELETE: 'clients.delete' as PermissionCode,
  },
  DOCUMENTS: {
    VIEW_ALL: 'documents.view_all' as PermissionCode,
    VIEW_ASSIGNED: 'documents.view_assigned' as PermissionCode,
    CREATE: 'documents.create' as PermissionCode,
    EDIT: 'documents.edit' as PermissionCode,
    DELETE: 'documents.delete' as PermissionCode,
  },
  INVOICES: {
    VIEW_ALL: 'invoices.view_all' as PermissionCode,
    VIEW_OWN: 'invoices.view_own' as PermissionCode,
    CREATE: 'invoices.create' as PermissionCode,
    EDIT: 'invoices.edit' as PermissionCode,
    DELETE: 'invoices.delete' as PermissionCode,
  },
  REPORTS: {
    VIEW_ALL: 'reports.view_all' as PermissionCode,
    VIEW_OWN: 'reports.view_own' as PermissionCode,
    AUDIT_LOGS: 'audit_logs.view' as PermissionCode,
  },
  HEARINGS: {
    VIEW_ALL: 'hearings.view_all' as PermissionCode,
    VIEW_ASSIGNED: 'hearings.view_assigned' as PermissionCode,
    MANAGE: 'hearings.manage' as PermissionCode,
  },
  BRANCHES: {
    CREATE: 'branches.create' as PermissionCode,
    READ: 'branches.read' as PermissionCode,
    UPDATE: 'branches.update' as PermissionCode,
    DELETE: 'branches.delete' as PermissionCode,
    ASSIGN_EMPLOYEES: 'branches.assign_employees' as PermissionCode,
  },
} as const;

// All permissions grouped by category
export const PERMISSION_CATEGORIES = {
  Firm: [PERMISSIONS.FIRM.MANAGE, PERMISSIONS.FIRM.VIEW_SETTINGS],
  Team: [PERMISSIONS.TEAM.INVITE, PERMISSIONS.TEAM.REMOVE, PERMISSIONS.TEAM.VIEW, PERMISSIONS.TEAM.CHANGE_ROLES],
  Cases: [PERMISSIONS.CASES.VIEW_ALL, PERMISSIONS.CASES.VIEW_ASSIGNED, PERMISSIONS.CASES.CREATE, PERMISSIONS.CASES.EDIT, PERMISSIONS.CASES.DELETE, PERMISSIONS.CASES.ASSIGN],
  Clients: [PERMISSIONS.CLIENTS.VIEW_ALL, PERMISSIONS.CLIENTS.VIEW_ASSIGNED, PERMISSIONS.CLIENTS.CREATE, PERMISSIONS.CLIENTS.EDIT, PERMISSIONS.CLIENTS.DELETE],
  Documents: [PERMISSIONS.DOCUMENTS.VIEW_ALL, PERMISSIONS.DOCUMENTS.VIEW_ASSIGNED, PERMISSIONS.DOCUMENTS.CREATE, PERMISSIONS.DOCUMENTS.EDIT, PERMISSIONS.DOCUMENTS.DELETE],
  Billing: [PERMISSIONS.INVOICES.VIEW_ALL, PERMISSIONS.INVOICES.VIEW_OWN, PERMISSIONS.INVOICES.CREATE, PERMISSIONS.INVOICES.EDIT, PERMISSIONS.INVOICES.DELETE],
  Reports: [PERMISSIONS.REPORTS.VIEW_ALL, PERMISSIONS.REPORTS.VIEW_OWN, PERMISSIONS.REPORTS.AUDIT_LOGS],
  Calendar: [PERMISSIONS.HEARINGS.VIEW_ALL, PERMISSIONS.HEARINGS.VIEW_ASSIGNED, PERMISSIONS.HEARINGS.MANAGE],
  Branches: [PERMISSIONS.BRANCHES.CREATE, PERMISSIONS.BRANCHES.READ, PERMISSIONS.BRANCHES.UPDATE, PERMISSIONS.BRANCHES.DELETE, PERMISSIONS.BRANCHES.ASSIGN_EMPLOYEES],
} as const;

// Default permissions for each role (used as fallback if DB is unavailable)
export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  owner: Object.values(PERMISSIONS).flatMap(Object.values),
  partner: [
    PERMISSIONS.FIRM.VIEW_SETTINGS,
    PERMISSIONS.TEAM.INVITE, PERMISSIONS.TEAM.REMOVE, PERMISSIONS.TEAM.VIEW,
    PERMISSIONS.CASES.VIEW_ALL, PERMISSIONS.CASES.VIEW_ASSIGNED, PERMISSIONS.CASES.CREATE, PERMISSIONS.CASES.EDIT, PERMISSIONS.CASES.DELETE, PERMISSIONS.CASES.ASSIGN,
    PERMISSIONS.CLIENTS.VIEW_ALL, PERMISSIONS.CLIENTS.VIEW_ASSIGNED, PERMISSIONS.CLIENTS.CREATE, PERMISSIONS.CLIENTS.EDIT, PERMISSIONS.CLIENTS.DELETE,
    PERMISSIONS.DOCUMENTS.VIEW_ALL, PERMISSIONS.DOCUMENTS.VIEW_ASSIGNED, PERMISSIONS.DOCUMENTS.CREATE, PERMISSIONS.DOCUMENTS.EDIT, PERMISSIONS.DOCUMENTS.DELETE,
    PERMISSIONS.INVOICES.VIEW_ALL, PERMISSIONS.INVOICES.VIEW_OWN, PERMISSIONS.INVOICES.CREATE, PERMISSIONS.INVOICES.EDIT,
    PERMISSIONS.REPORTS.VIEW_ALL, PERMISSIONS.REPORTS.VIEW_OWN, PERMISSIONS.REPORTS.AUDIT_LOGS,
    PERMISSIONS.HEARINGS.VIEW_ALL, PERMISSIONS.HEARINGS.VIEW_ASSIGNED, PERMISSIONS.HEARINGS.MANAGE,
    PERMISSIONS.BRANCHES.CREATE, PERMISSIONS.BRANCHES.READ, PERMISSIONS.BRANCHES.UPDATE, PERMISSIONS.BRANCHES.DELETE, PERMISSIONS.BRANCHES.ASSIGN_EMPLOYEES,
  ],
  senior_associate: [
    PERMISSIONS.FIRM.VIEW_SETTINGS,
    PERMISSIONS.TEAM.VIEW,
    PERMISSIONS.CASES.VIEW_ALL, PERMISSIONS.CASES.VIEW_ASSIGNED, PERMISSIONS.CASES.CREATE, PERMISSIONS.CASES.EDIT, PERMISSIONS.CASES.ASSIGN,
    PERMISSIONS.CLIENTS.VIEW_ALL, PERMISSIONS.CLIENTS.VIEW_ASSIGNED, PERMISSIONS.CLIENTS.CREATE, PERMISSIONS.CLIENTS.EDIT,
    PERMISSIONS.DOCUMENTS.VIEW_ALL, PERMISSIONS.DOCUMENTS.VIEW_ASSIGNED, PERMISSIONS.DOCUMENTS.CREATE, PERMISSIONS.DOCUMENTS.EDIT, PERMISSIONS.DOCUMENTS.DELETE,
    PERMISSIONS.INVOICES.VIEW_ALL, PERMISSIONS.INVOICES.VIEW_OWN, PERMISSIONS.INVOICES.CREATE,
    PERMISSIONS.REPORTS.VIEW_ALL, PERMISSIONS.REPORTS.VIEW_OWN,
    PERMISSIONS.HEARINGS.VIEW_ALL, PERMISSIONS.HEARINGS.VIEW_ASSIGNED, PERMISSIONS.HEARINGS.MANAGE,
  ],
  associate: [
    PERMISSIONS.TEAM.VIEW,
    PERMISSIONS.CASES.VIEW_ASSIGNED, PERMISSIONS.CASES.CREATE, PERMISSIONS.CASES.EDIT,
    PERMISSIONS.CLIENTS.VIEW_ASSIGNED, PERMISSIONS.CLIENTS.CREATE, PERMISSIONS.CLIENTS.EDIT,
    PERMISSIONS.DOCUMENTS.VIEW_ASSIGNED, PERMISSIONS.DOCUMENTS.CREATE, PERMISSIONS.DOCUMENTS.EDIT,
    PERMISSIONS.INVOICES.VIEW_OWN,
    PERMISSIONS.REPORTS.VIEW_OWN,
    PERMISSIONS.HEARINGS.VIEW_ASSIGNED, PERMISSIONS.HEARINGS.MANAGE,
  ],
  junior_associate: [
    PERMISSIONS.TEAM.VIEW,
    PERMISSIONS.CASES.VIEW_ASSIGNED,
    PERMISSIONS.CLIENTS.VIEW_ASSIGNED,
    PERMISSIONS.DOCUMENTS.VIEW_ASSIGNED, PERMISSIONS.DOCUMENTS.CREATE, PERMISSIONS.DOCUMENTS.EDIT,
    PERMISSIONS.HEARINGS.VIEW_ASSIGNED,
  ],
  paralegal: [
    PERMISSIONS.TEAM.VIEW,
    PERMISSIONS.CASES.VIEW_ASSIGNED,
    PERMISSIONS.CLIENTS.VIEW_ASSIGNED,
    PERMISSIONS.DOCUMENTS.VIEW_ASSIGNED, PERMISSIONS.DOCUMENTS.CREATE, PERMISSIONS.DOCUMENTS.EDIT,
    PERMISSIONS.HEARINGS.VIEW_ASSIGNED,
  ],
  intern: [
    PERMISSIONS.TEAM.VIEW,
    PERMISSIONS.CASES.VIEW_ASSIGNED,
    PERMISSIONS.CLIENTS.VIEW_ASSIGNED,
    PERMISSIONS.DOCUMENTS.VIEW_ASSIGNED,
    PERMISSIONS.HEARINGS.VIEW_ASSIGNED,
  ],
  office_admin: [
    PERMISSIONS.FIRM.VIEW_SETTINGS,
    PERMISSIONS.TEAM.VIEW,
    PERMISSIONS.INVOICES.VIEW_ALL, PERMISSIONS.INVOICES.VIEW_OWN, PERMISSIONS.INVOICES.CREATE, PERMISSIONS.INVOICES.EDIT,
    PERMISSIONS.REPORTS.VIEW_ALL, PERMISSIONS.REPORTS.VIEW_OWN,
    PERMISSIONS.BRANCHES.READ,
  ],
};
