import jsPDF from "jspdf";

interface LegalDocOptions {
  title: string;
  content: string;
  courtName?: string;
  caseNumber?: string;
  jurisdiction?: string;
}

export function generateLegalDocPDF(options: LegalDocOptions): jsPDF {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 25;
  const marginRight = 25;
  const marginTop = 25;
  const marginBottom = 25;
  const contentWidth = pageWidth - marginLeft - marginRight;
  let y = marginTop;

  // Header
  doc.setFont("times", "bold");
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text(options.title.toUpperCase(), pageWidth / 2, y, { align: "center" });
  y += 8;

  // Court name and case number
  if (options.courtName) {
    doc.setFont("times", "normal");
    doc.setFontSize(11);
    doc.text(options.courtName, pageWidth / 2, y, { align: "center" });
    y += 6;
  }

  if (options.caseNumber) {
    doc.setFont("times", "normal");
    doc.setFontSize(10);
    doc.text(options.caseNumber, pageWidth / 2, y, { align: "center" });
    y += 6;
  }

  // Divider line
  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 10;

  // Body content
  doc.setFont("times", "normal");
  doc.setFontSize(12);
  doc.setTextColor(0);

  const lines = doc.splitTextToSize(options.content, contentWidth);

  for (const line of lines) {
    if (y > pageHeight - marginBottom) {
      doc.addPage();
      y = marginTop;
    }
    doc.text(line, marginLeft, y);
    y += 6;
  }

  // Footer on each page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("times", "normal");
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
    doc.text(
      "Generated by CaseFiles Legal Practice Management",
      pageWidth / 2,
      pageHeight - 6,
      { align: "center" }
    );
  }

  return doc;
}

export function downloadLegalDocPDF(
  options: LegalDocOptions,
  filename: string = "legal-document.pdf"
): void {
  const doc = generateLegalDocPDF(options);
  doc.save(filename);
}
