// Section mappings for common Indian Acts
// Maps section numbers to topics/descriptions

export interface SectionInfo {
  section: string;
  title: string;
  description: string;
}

export const ACT_SECTIONS: Record<string, Record<string, SectionInfo>> = {
  "Indian Penal Code": {
    "34": { section: "34", title: "Common Intention", description: "Acts done by several persons in furtherance of common intention" },
    "120A": { section: "120A", title: "Criminal Conspiracy", description: "Definition of criminal conspiracy" },
    "120B": { section: "120B", title: "Punishment for Criminal Conspiracy", description: "Punishment for criminal conspiracy" },
    "141": { section: "141", title: "Unlawful Assembly", description: "Definition of unlawful assembly" },
    "149": { section: "149", title: "Every member of unlawful assembly guilty of offence", description: "Every member of unlawful assembly guilty of offence committed in prosecution of common object" },
    "147": { section: "147", title: "Rioting", description: "Punishment for rioting" },
    "148": { section: "148", title: "Rioting with deadly weapon", description: "Rioting armed with deadly weapon" },
    "166": { section: "166", title: "Public servant disobeying law", description: "Public servant disobeying direction of law" },
    "167": { section: "167", title: "Public servant framing incorrect document", description: "Public servant framing incorrect document with intent to cause injury" },
    "299": { section: "299", title: "Culpable Homicide", description: "Culpable homicide" },
    "300": { section: "300", title: "Murder", description: "Murder" },
    "302": { section: "302", title: "Punishment for Murder", description: "Punishment for murder — death or life imprisonment" },
    "304": { section: "304", title: "Culpable Homicide not amounting to Murder", description: "Punishment for culpable homicide not amounting to murder" },
    "304A": { section: "304A", title: "Causing Death by Negligence", description: "Causing death by rash and negligent act" },
    "306": { section: "306", title: "Abetment of Suicide", description: "Abetment of suicide" },
    "307": { section: "307", title: "Attempt to Murder", description: "Attempt to murder" },
    "309": { section: "309", title: "Attempt to Commit Suicide", description: "Attempt to commit suicide" },
    "323": { section: "323", title: "Punishment for Voluntarily Causing Hurt", description: "Punishment for voluntarily causing hurt" },
    "324": { section: "324", title: "Voluntarily Causing Hurt by dangerous weapons", description: "Voluntarily causing hurt by dangerous weapons or means" },
    "325": { section: "325", title: "Punishment for Voluntarily Causing Grievous Hurt", description: "Punishment for voluntarily causing grievous hurt" },
    "326": { section: "326", title: "Voluntarily Causing Grievous Hurt by dangerous weapons", description: "Voluntarily causing grievous hurt by dangerous weapons or means" },
    "341": { section: "341", title: "Punishment for Wrongful Restraint", description: "Punishment for wrongful restraint" },
    "342": { section: "342", title: "Punishment for Wrongful Confinement", description: "Punishment for wrongful confinement" },
    "354": { section: "354", title: "Assault on woman with intent to outrage modesty", description: "Assault or criminal force to woman with intent to outrage her modesty" },
    "354A": { section: "354A", title: "Sexual Harassment", description: "Sexual harassment — punishment" },
    "354B": { section: "354B", title: "Assault on woman with intent to disrobe", description: "Assault or use of criminal force to woman with intent to disrobe" },
    "354C": { section: "354C", title: "Voyeurism", description: "Watching or capturing images of woman engaging in private act" },
    "354D": { section: "354D", title: "Stalking", description: "Stalking — punishment" },
    "375": { section: "375", title: "Rape", description: "Definition of rape" },
    "376": { section: "376", title: "Punishment for Rape", description: "Punishment for sexual assault" },
    "376A": { section: "376A", title: "Rape causing death or persistent vegetative state", description: "Punishment for rape causing death or resulting in persistent vegetative state" },
    "376B": { section: "376B", title: "Sexual intercourse by husband upon wife", description: "Sexual intercourse by husband upon wife during separation" },
    "376C": { section: "376C", title: "Sexual intercourse by person in authority", description: "Sexual intercourse by person in authority" },
    "376D": { section: "376D", title: "Gang Rape", description: "Punishment for gang rape" },
    "379": { section: "379", title: "Theft", description: "Punishment for theft" },
    "380": { section: "380", title: "Theft in dwelling house", description: "Theft in dwelling house, etc." },
    "384": { section: "384", title: "Extortion", description: "Punishment for extortion" },
    "392": { section: "392", title: "Robbery", description: "Punishment for robbery" },
    "395": { section: "395", title: "Dacoity", description: "Punishment for dacoity" },
    "406": { section: "406", title: "Criminal Breach of Trust", description: "Punishment for criminal breach of trust" },
    "415": { section: "415", title: "Cheating", description: "Definition of cheating" },
    "420": { section: "420", title: "Cheating and dishonestly inducing delivery of property", description: "Cheating and dishonestly inducing delivery of property" },
    "441": { section: "441", title: "Criminal Trespass", description: "Definition of criminal trespass" },
    "447": { section: "447", title: "Punishment for Criminal Trespass", description: "Punishment for criminal trespass" },
    "448": { section: "448", title: "House Trespass", description: "Punishment for house trespass" },
    "463": { section: "463", title: "Forgery", description: "Definition of forgery" },
    "465": { section: "465", title: "Punishment for Forgery", description: "Punishment for forgery" },
    "468": { section: "468", title: "Forgery for purpose of cheating", description: "Forgery for purpose of cheating" },
    "471": { section: "471", title: "Using forged document as genuine", description: "Using as genuine a forged document or electronic record" },
    "482": { section: "482", title: "Using false mark on goods", description: "Using false mark or denomination on goods" },
    "493": { section: "493", title: "Cohabitation caused by deceitfully induced belief", description: "Cohabitation caused by deceitfully induced belief of lawful marriage" },
    "494": { section: "494", title: "Marrying again during lifetime of husband or wife", description: "Marrying again during lifetime of husband or wife" },
    "498A": { section: "498A", title: "Cruelty by Husband or Relatives", description: "Cruelty or harassment by husband or his relatives" },
    "500": { section: "500", title: "Defamation", description: "Punishment for defamation" },
    "503": { section: "503", title: "Criminal Intimidation", description: "Criminal intimidation" },
    "504": { section: "504", title: "Intentional insult to provoke breach of peace", description: "Intentional insult with intent to provoke breach of the peace" },
    "506": { section: "506", title: "Punishment for Criminal Intimidation", description: "Punishment for criminal intimidation" },
    "509": { section: "509", title: "Word, gesture or act intended to insult modesty of a woman", description: "Word, gesture or act intended to insult the modesty of a woman" },
  },
  "Bharatiya Nyaya Sanhita": {
    "34": { section: "34", title: "Common Intention", description: "Acts done by several persons in furtherance of common intention" },
    "61": { section: "61", title: "Criminal Conspiracy", description: "Definition of criminal conspiracy" },
    "62": { section: "62", title: "Punishment for Criminal Conspiracy", description: "Punishment for criminal conspiracy" },
    "189": { section: "189", title: "Unlawful Assembly", description: "Definition of unlawful assembly" },
    "190": { section: "190", title: "Every member of unlawful assembly guilty", description: "Every member of unlawful assembly guilty of offence" },
    "191": { section: "191", title: "Rioting", description: "Punishment for rioting" },
    "223": { section: "223", title: "Culpable Homicide", description: "Culpable homicide" },
    "224": { section: "224", title: "Murder", description: "Murder" },
    "225": { section: "225", title: "Punishment for Murder", description: "Punishment for murder — death or life imprisonment" },
    "227": { section: "227", title: "Culpable Homicide not amounting to Murder", description: "Punishment for culpable homicide not amounting to murder" },
    "229": { section: "229", title: "Causing Death by Negligence", description: "Causing death by rash and negligent act" },
    "231": { section: "231", title: "Attempt to Murder", description: "Attempt to murder" },
    "248": { section: "248", title: "Voluntarily Causing Hurt", description: "Punishment for voluntarily causing hurt" },
    "249": { section: "249", title: "Voluntarily Causing Hurt by dangerous weapons", description: "Voluntarily causing hurt by dangerous weapons" },
    "250": { section: "250", title: "Voluntarily Causing Grievous Hurt", description: "Punishment for voluntarily causing grievous hurt" },
    "251": { section: "251", title: "Voluntarily Causing Grievous Hurt by dangerous weapons", description: "Voluntarily causing grievous hurt by dangerous weapons" },
    "263": { section: "263", title: "Wrongful Restraint", description: "Punishment for wrongful restraint" },
    "264": { section: "264", title: "Wrongful Confinement", description: "Punishment for wrongful confinement" },
    "274": { section: "274", title: "Assault on woman to outrage modesty", description: "Assault on woman with intent to outrage modesty" },
    "275": { section: "275", title: "Sexual Harassment", description: "Sexual harassment" },
    "276": { section: "276", title: "Assault on woman to disrobe", description: "Assault to disrobe a woman" },
    "277": { section: "277", title: "Voyeurism", description: "Watching or capturing images of woman engaging in private act" },
    "278": { section: "278", title: "Stalking", description: "Stalking" },
    "63": { section: "63", title: "Rape", description: "Definition of rape" },
    "64": { section: "64", title: "Punishment for Rape", description: "Punishment for sexual assault" },
    "69": { section: "69", title: "Sexual intercourse by husband upon wife during separation", description: "Sexual intercourse by husband upon wife during separation" },
    "70": { section: "70", title: "Gang Rape", description: "Punishment for gang rape" },
    "303": { section: "303", title: "Theft", description: "Punishment for theft" },
    "304": { section: "304", title: "Theft in dwelling house", description: "Theft in dwelling house" },
    "308": { section: "308", title: "Extortion", description: "Punishment for extortion" },
    "309": { section: "309", title: "Robbery", description: "Punishment for robbery" },
    "310": { section: "310", title: "Dacoity", description: "Punishment for dacoity" },
    "316": { section: "316", title: "Criminal Breach of Trust", description: "Punishment for criminal breach of trust" },
    "318": { section: "318", title: "Cheating", description: "Definition of cheating" },
    "319": { section: "319", title: "Cheating and dishonestly inducing delivery of property", description: "Cheating and dishonestly inducing delivery of property" },
    "329": { section: "329", title: "Criminal Trespass", description: "Definition of criminal trespass" },
    "330": { section: "330", title: "Punishment for Criminal Trespass", description: "Punishment for criminal trespass" },
    "331": { section: "331", title: "House Trespass", description: "Punishment for house trespass" },
    "338": { section: "338", title: "Forgery", description: "Definition of forgery" },
    "340": { section: "340", title: "Punishment for Forgery", description: "Punishment for forgery" },
    "341": { section: "341", title: "Forgery for purpose of cheating", description: "Forgery for purpose of cheating" },
    "344": { section: "344", title: "Using forged document as genuine", description: "Using as genuine a forged document" },
    "352": { section: "352", title: "Cruelty by Husband or Relatives", description: "Cruelty or harassment by husband or his relatives" },
    "356": { section: "356", title: "Defamation", description: "Punishment for defamation" },
    "358": { section: "358", title: "Criminal Intimidation", description: "Criminal intimidation" },
    "359": { section: "359", title: "Intentional insult to provoke breach of peace", description: "Intentional insult with intent to provoke breach of the peace" },
    "361": { section: "361", title: "Punishment for Criminal Intimidation", description: "Punishment for criminal intimidation" },
    "364": { section: "364", title: "Word or act to insult modesty of a woman", description: "Word, gesture or act intended to insult the modesty of a woman" },
  },
  "Code of Criminal Procedure": {
    "41A": { section: "41A", title: "Notice of appearance before police officer", description: "Notice of appearance before police officer" },
    "41B": { section: "41B", title: "Procedure of arrest and memorandum", description: "Procedure of arrest and memorandum of arrest" },
    "43": { section: "43", title: "Arrest by private person", description: "Arrest by private person without warrant" },
    "46": { section: "46", title: "Arrest how made", description: "Arrest how made" },
    "50": { section: "50", title: "Arrested person to be informed of grounds", description: "Arrested person to be informed of grounds of arrest" },
    "54": { section: "54", title: "Examination of arrested person by medical practitioner", description: "Examination of arrested person by medical practitioner" },
    "55A": { section: "55A", title: "Health and safety of arrested person", description: "Health and safety of arrested person" },
    "57": { section: "57", title: "Person arrested not to be detained more than 24 hours", description: "Person arrested not to be detained more than twenty-four hours" },
    "82": { section: "82", title: "Proclamation for absconding person", description: "Proclamation for person absconding" },
    "87": { section: "87", title: "Warrant may be issued in certain cases", description: "Warrant may be issued in certain cases" },
    "91": { section: "91", title: "Summons to produce document", description: "Summons to produce document or other thing" },
    "93": { section: "93", title: "When search warrant may be issued", description: "When search warrant may be issued" },
    "100": { section: "100", title: "Search by police officer", description: "Search by police officer" },
    "107": { section: "107", title: "Security for keeping the peace", description: "Security for keeping the peace and for good behaviour" },
    "108": { section: "108", title: "Security for good behaviour from suspected persons", description: "Security for good behaviour from suspected persons" },
    "109": { section: "109", title: "Security for good behaviour from habitual offenders", description: "Security for good behaviour from habitual offenders" },
    "110": { section: "110", title: "Security for good behaviour from habitual offenders", description: "Security for good behaviour from habitual offenders" },
    "125": { section: "125", title: "Order for maintenance of wives, children and parents", description: "Order for maintenance of wives, children and parents" },
    "125A": { section: "125A", title: "Penalty for default of payment of maintenance", description: "Penalty for default of payment of maintenance" },
    "133": { section: "133", title: "Conditional order for removal of nuisance", description: "Conditional order for removal of nuisance" },
    "144": { section: "144", title: "Power to issue order in urgent cases of nuisance", description: "Power to issue order in urgent cases of nuisance or apprehended danger" },
    "145": { section: "145", title: "Dispute concerning land or water", description: "Dispute concerning land or water — procedure" },
    "154": { section: "154", title: "Information in cognizable cases", description: "Information in cognizable cases (FIR)" },
    "155": { section: "155", title: "Information in non-cognizable cases", description: "Information in non-cognizable cases" },
    "156": { section: "156", title: "Police officer's power to investigate cognizable case", description: "Police officer's power to investigate cognizable case" },
    "160": { section: "160", title: "Police officer's power to require attendance of witnesses", description: "Police officer's power to require attendance of witnesses" },
    "161": { section: "161", title: "Examination of witnesses by police", description: "Examination of witnesses by police" },
    "162": { section: "162", title: "Statements of witnesses to be in writing", description: "Statements of witnesses to be in writing" },
    "164": { section: "164", title: "Recording of confessions and statements", description: "Recording of confessions and statements by Magistrate" },
    "167": { section: "167", title: "Procedure when investigation cannot be completed in 24 hours", description: "Procedure when investigation cannot be completed in twenty-four hours" },
    "173": { section: "173", title: "Report of police officer on completion of investigation", description: "Report of police officer on completion of investigation" },
    "190": { section: "190", title: "Cognizance of offences by Magistrate", description: "Cognizance of offences by Magistrate" },
    "197": { section: "197", title: "Prosecution of Judges and public servants", description: "Prosecution of Judges and public servants" },
    "200": { section: "200", title: "Prosecution of offences on complaint", description: "Prosecution of offences on complaint to Magistrate" },
    "202": { section: "202", title: "Postponement of issue of process", description: "Postponement of issue of process" },
    "204": { section: "204", title: "Issue of process", description: "Issue of process by Magistrate" },
    "209": { section: "209", title: "Commitment of case to High Court or Court of Session", description: "Commitment of case to High Court or Court of Session" },
    "213": { section: "213", title: "Form of charge", description: "Form of charge" },
    "218": { section: "218", title: "Joinder of charges", description: "Joinder of charges" },
    "223": { section: "223", title: "When several charges may be tried together", description: "When several charges may be tried together" },
    "233": { section: "233", title: "Accused may be examined", description: "Accused may be examined" },
    "234": { section: "234", title: "Arguments of prosecution and defence", description: "Arguments of prosecution and defence" },
    "235": { section: "235", title: "Judgment of acquittal or conviction", description: "Judgment of acquittal or conviction" },
    "248": { section: "248", title: "Acquittal or discharge of accused", description: "Acquittal or discharge of accused when complainant absent" },
    "249": { section: "249", title: "Discharge of accused", description: "Discharge of accused" },
    "250": { section: "250", title: "Compensation for accusation without reasonable cause", description: "Compensation for accusation without reasonable cause" },
    "255A": { section: "255A", title: "Application of provisions of sections 248 and 249", description: "Application of provisions of sections 248 and 249" },
    "260": { section: "260", title: "Power of Magistrate to try cases summarily", description: "Power of Magistrate to try cases summarily" },
    "302": { section: "302", title: "Power of Magistrate to sentence to imprisonment", description: "Power of Magistrate to sentence to imprisonment for life" },
    "309": { section: "309", title: "Power to postpone or adjourn proceedings", description: "Power to postpone or adjourn proceedings" },
    "313": { section: "313", title: "Power to examine the accused", description: "Power to examine the accused" },
    "319": { section: "319", title: "Power to proceed against other persons", description: "Power to proceed against other persons appearing to be guilty" },
    "320": { section: "320", title: "Compounding of offences", description: "Compounding of offences" },
    "321": { section: "321", title: "Withdrawal of prosecution", description: "Withdrawal of prosecution by Public Prosecutor" },
    "340": { section: "340", title: "Prosecution for offences against justice", description: "Prosecution for offences against justice" },
    "372": { section: "372", title: "No appeal in certain cases when accused pleads guilty", description: "No appeal in certain cases when accused pleads guilty" },
    "374": { section: "374", title: "Appeals from convictions", description: "Appeals from convictions by Magistrates" },
    "378": { section: "378", title: "Appeal in cases of acquittal", description: "Appeal in cases of acquittal" },
    "386": { section: "386", title: "Power of Appellate Court to reverse or alter finding", description: "Power of Appellate Court to reverse or alter finding or sentence" },
    "389": { section: "389", title: "Suspension of sentence pending appeal", description: "Suspension of sentence pending appeal" },
    "397": { section: "397", title: "Calling for records to examine cases", description: "Calling for records to examine cases" },
    "401": { section: "401", title: "High Court's power to quash proceedings", description: "High Court's power of revision" },
    "407": { section: "407", title: "High Court's power to transfer cases", description: "High Court's power to transfer cases and appeals" },
    "482": { section: "482", title: "Saving of inherent power of High Court", description: "Saving of inherent power of High Court to quash proceedings" },
    "498": { section: "498", title: "Husband or relative of husband subjecting woman to cruelty", description: "Husband or relative of husband subjecting woman to cruelty" },
  },
  "Code of Civil Procedure": {
    "9": { section: "9", title: "Courts to try all civil suits", description: "Courts to try all civil suits unless barred" },
    "10": { section: "10", title: "Stay of suit", description: "Stay of suit — res sub judice" },
    "11": { section: "11", title: "Res judicata", description: "Res judicata" },
    "15": { section: "15", title: "Court of first instance", description: "Court of first instance" },
    "20": { section: "20", title: "Other suits to be instituted where defendant resides", description: "Other suits to be instituted where defendant resides or cause of action arises" },
    "26": { section: "26", title: "Institution of suits", description: "Institution of suits" },
    "31": { section: "31", title: "Pauper suits", description: "Suits by paupers" },
    "35": { section: "35", title: "Costs", description: "Costs" },
    "35A": { section: "35A", title: "Compensatory costs in certain cases", description: "Compensatory costs in certain cases" },
    "35B": { section: "35B", title: "Costs for causing delay", description: "Costs for causing delay" },
    "37": { section: "37", title: "Decree", description: "Definition of decree" },
    "38": { section: "38", title: "Decree-holder", description: "Definition of decree-holder" },
    "39": { section: "39", title: "Representative suits", description: "Representative suits" },
    "47": { section: "47", title: "Questions to be determined by Court executing decree", description: "Questions to be determined by Court executing decree" },
    "94": { section: "94", title: "Arrest and attachment before judgment", description: "Arrest and attachment before judgment" },
    "95": { section: "95", title: "Compensation for obtaining arrest, attachment or injunction on insufficient grounds", description: "Compensation for obtaining arrest, attachment or injunction on insufficient grounds" },
    "96": { section: "96", title: "Appeal from original decree", description: "Appeal from original decree" },
    "100": { section: "100", title: "Second appeal", description: "Second appeal — substantial question of law" },
    "102": { section: "102", title: "No second appeal in certain cases", description: "No second appeal in certain cases" },
    "104": { section: "104", title: "Orders from which appeal lies", description: "Orders from which appeal lies" },
    "107": { section: "107", title: "Powers of appellate Court", description: "Powers of appellate Court" },
    "108": { section: "108", title: "Remand", description: "Remand" },
    "114": { section: "114", title: "Review", description: "Review of judgment" },
    "115": { section: "115", title: "Revision", description: "Revisional power of High Court" },
    "133": { section: "133", title: "Conditional order for removal of nuisance", description: "Conditional order for removal of nuisance" },
    "134": { section: "134", title: "Consequence of disobedience", description: "Consequence of disobedience or breach" },
    "135": { section: "135", title: "Disobedience of injunction", description: "Disobedience of injunction" },
    "136": { section: "136", title: "Arrest and attachment", description: "Arrest and attachment for disobedience" },
    "138": { section: "138", title: "Application of Order XXI", description: "Application of Order XXI" },
    "141": { section: "141", title: "Incidental proceedings", description: "Incidental proceedings" },
    "148": { section: "148", title: "Enlargement of time", description: "Enlargement of time" },
    "151": { section: "151", title: "Inherent powers of Court", description: "Saving of inherent power of Court" },
  },
  "Indian Evidence Act": {
    "3": { section: "3", title: "Definitions", description: "Definitions in Evidence Act" },
    "5": { section: "5", title: "Evidence may be given of facts in issue", description: "Evidence may be given of facts in issue and relevant facts" },
    "6": { section: "6", title: "Relevancy of facts forming part of same transaction", description: "Relevancy of facts forming part of same transaction" },
    "8": { section: "8", title: "Facts showing state of mind", description: "Facts showing state of mind or body" },
    "9": { section: "9", title: "Facts necessary to explain or introduce relevant facts", description: "Facts necessary to explain or introduce relevant facts" },
    "11": { section: "11", title: "Facts tending to render facts in issue improbable", description: "Facts tending to render facts in issue improbable" },
    "13": { section: "13", title: "Facts showing existence of right or custom", description: "Facts showing existence of right or custom" },
    "14": { section: "14", title: "Facts showing motive or preparation", description: "Facts showing motive or preparation" },
    "15": { section: "15", title: "Facts showing conduct in conformity with existing belief", description: "Facts showing conduct in conformity with existing belief" },
    "17": { section: "17", title: "Admission defined", description: "Admission defined" },
    "21": { section: "21", title: "Proof of admissions against persons making them", description: "Proof of admissions against persons making them" },
    "23": { section: "23", title: "Admissions not relevant in certain civil proceedings", description: "Admissions not relevant in certain civil proceedings" },
    "24": { section: "24", title: "Confession caused by inducement, threat or promise", description: "Confession caused by inducement, threat or promise" },
    "25": { section: "25", title: "Confession to police officer not to be proved", description: "Confession to police officer not to be proved" },
    "26": { section: "26", title: "Confession by accused while in custody", description: "Confession by accused while in custody not to be proved" },
    "27": { section: "27", title: "How much of information may be proved", description: "How much of information received from accused may be proved" },
    "29": { section: "29", title: "Confession made after removal of impression", description: "Confession made after removal of impression caused by inducement" },
    "30": { section: "30", title: "Consideration of proved confession affecting person making it", description: "Consideration of proved confession affecting person making it" },
    "32": { section: "32", title: "Statements in dying declarations", description: "Statements made in dying declarations" },
    "33": { section: "33", title: "Relevancy of certain evidence for proving truth of facts", description: "Relevancy of certain evidence for proving truth of facts" },
    "45": { section: "45", title: "Opinion of experts", description: "Opinion of experts" },
    "46": { section: "46", title: "Facts bearing upon opinion of experts", description: "Facts bearing upon opinion of experts" },
    "47": { section: "47", title: "Opinion as to handwriting", description: "Opinion as to handwriting" },
    "48": { section: "48", title: "Opinion as to usage or right", description: "Opinion as to usage or right" },
    "49": { section: "49", title: "Opinion on relationship", description: "Opinion on relationship" },
    "50": { section: "50", title: "Opinion on foreign law", description: "Opinion on foreign law" },
    "51": { section: "51", title: "Grounds of opinion", description: "Grounds of opinion" },
    "52": { section: "52", title: "When opinions of experts may be given", description: "When opinions of experts may be given" },
    "53": { section: "53", title: "When opinions of experts may be given", description: "When opinions of experts may be given" },
    "54": { section: "54", title: "Previous convictions as evidence", description: "Previous convictions as evidence" },
    "55": { section: "55", title: "Previous convictions as evidence", description: "Previous convictions as evidence" },
    "57": { section: "57", title: "Court may refer to records for its opinion", description: "Court may refer to records for its opinion" },
    "58": { section: "58", title: "No evidence needed of fact admitted", description: "No evidence needed of fact admitted" },
    "59": { section: "59", title: "All facts may be proved except", description: "All facts may be proved except" },
    "60": { section: "60", title: "Oral evidence must be direct", description: "Oral evidence must be direct" },
    "61": { section: "61", title: "Proof of contents of documents", description: "Proof of contents of documents" },
    "62": { section: "62", title: "Primary evidence", description: "Primary evidence" },
    "63": { section: "63", title: "Secondary evidence", description: "Secondary evidence" },
    "64": { section: "64", title: "Proof of documents by primary evidence", description: "Proof of documents by primary evidence" },
    "65": { section: "65", title: "Cases in which secondary evidence may be given", description: "Cases in which secondary evidence may be given" },
    "65B": { section: "65B", title: "Admissibility of electronic records", description: "Admissibility of electronic records" },
    "67": { section: "67", title: "Proof of signature of person executing document", description: "Proof of signature of person executing document" },
    "71": { section: "71", title: "Proof of attestation", description: "Proof of attestation" },
    "73": { section: "73", title: "Comparison of signature, writing or seal", description: "Comparison of signature, writing or seal" },
    "74": { section: "74", title: "Documentary evidence", description: "Documentary evidence" },
    "85": { section: "85", title: "Presumption as to genuineness of certified copies", description: "Presumption as to genuineness of certified copies" },
    "86": { section: "86", title: "Presumption as to genuineness of documents", description: "Presumption as to genuineness of documents" },
    "90": { section: "90", title: "Presumption as to genuineness of ancient documents", description: "Presumption as to genuineness of ancient documents" },
    "91": { section: "91", title: "Exclusion of oral evidence where document proves the fact", description: "Exclusion of oral evidence where document proves the fact" },
    "92": { section: "92", title: "Exclusion of evidence of oral agreement", description: "Exclusion of evidence of oral agreement" },
    "93": { section: "93", title: "Exclusion of evidence to explain or amend ambiguous document", description: "Exclusion of evidence to explain or amend ambiguous document" },
    "94": { section: "94", title: "Exclusion of evidence against application of document", description: "Exclusion of evidence against application of document" },
    "95": { section: "95", title: "Exclusion of evidence to prove terms of writing", description: "Exclusion of evidence to prove terms of writing" },
    "97": { section: "97", title: "Exclusion of evidence to explain varying terms of document", description: "Exclusion of evidence to explain varying terms of document" },
    "100": { section: "100", title: "Witnesses", description: "Who may testify" },
    "101": { section: "101", title: "Burden of proof", description: "Burden of proof" },
    "102": { section: "102", title: "On whom burden of proof lies", description: "On whom burden of proof lies" },
    "103": { section: "103", title: "Burden of proving case to be within exception", description: "Burden of proving case to be within exception" },
    "104": { section: "104", title: "Burden of proving fact to be proved", description: "Burden of proving fact to be proved" },
    "105": { section: "105", title: "Burden of proving offence to have been committed", description: "Burden of proving offence to have been committed by person charged" },
    "106": { section: "106", title: "Burden of proving fact to be within exception", description: "Burden of proving fact to be within exception" },
    "113": { section: "113", title: "Burden of proving fact to be proved", description: "Burden of proving fact to be proved to make evidence admissible" },
    "114": { section: "114", title: "Court may presume existence of certain facts", description: "Court may presume existence of certain facts" },
    "115": { section: "115", title: "Estoppel", description: "Estoppel" },
    "116": { section: "116", title: "Estoppel of tenant", description: "Estoppel of tenant" },
    "117": { section: "117", title: "Estoppel of bailee or licensee", description: "Estoppel of bailee or licensee" },
    "118": { section: "118", title: "Who may testify", description: "Who may testify" },
    "119": { section: "119", title: "Dumb witnesses", description: "Dumb witnesses" },
    "120": { section: "120", title: "Accused may be a competent witness", description: "Accused may be a competent witness" },
    "121": { section: "121", title: "Judges and Magistrates", description: "Judges and Magistrates not compelled to give evidence" },
    "122": { section: "122", title: "Communications during marriage", description: "Communications during marriage" },
    "123": { section: "123", title: "Evidence as to affairs of State", description: "Evidence as to affairs of State" },
    "124": { section: "124", title: "Official communications", description: "Official communications" },
    "125": { section: "125", title: "Indecent or libellous matter", description: "Indecent or libellous matter" },
    "126": { section: "126", title: "Professional communications", description: "Professional communications" },
    "127": { section: "127", title: "Section 126 to apply tointerpreters", description: "Section 126 to apply to interpreters" },
    "128": { section: "128", title: "Privilege not waived by volunteering evidence", description: "Privilege not waived by volunteering evidence" },
    "129": { section: "129", title: "Confidential communications with legal advisers", description: "Confidential communications with legal advisers" },
    "130": { section: "130", title: "Privilege as to affairs of State", description: "Privilege as to affairs of State" },
    "131": { section: "131", title: "Witness not compellable to disclose communication with accused", description: "Witness not compellable to disclose communication with accused" },
    "132": { section: "132", title: "Witness not excused from answering", description: "Witness not excused from answering" },
    "133": { section: "133", title: "Accomplice", description: "Accomplice — may be a competent witness" },
    "134": { section: "134", title: "Number of witnesses", description: "Number of witnesses" },
    "135": { section: "135", title: "Order of examination of witnesses", description: "Order of examination of witnesses" },
    "137": { section: "137", title: "Examination-in-chief", description: "Examination-in-chief" },
    "138": { section: "138", title: "Cross-examination", description: "Cross-examination" },
    "140": { section: "140", title: "Leading questions", description: "Leading questions" },
    "142": { section: "142", title: "Questions lawful in cross-examination", description: "Questions lawful in cross-examination" },
    "143": { section: "143", title: "Questions not to be asked without reasonable grounds", description: "Questions not to be asked without reasonable grounds" },
    "145": { section: "145", title: "Cross-examination as to previous statements", description: "Cross-examination as to previous statements in writing" },
    "146": { section: "146", title: "Questions lawful in cross-examination", description: "Questions lawful in cross-examination" },
    "148": { section: "148", title: "Cross-examination of witness as to credit", description: "Cross-examination of witness as to credit" },
    "149": { section: "149", title: "Indecent and scandalous questions", description: "Indecent and scandalous questions" },
    "150": { section: "150", title: "Questions intended to insult or annoy", description: "Questions intended to insult or annoy" },
    "151": { section: "151", title: "Power to prohibit", description: "Court may prohibit certain questions" },
    "152": { section: "152", title: "Evidence as to matters in writing", description: "Evidence as to matters in writing" },
    "153": { section: "153", title: "Exclusion of evidence to contradict answers to questions", description: "Exclusion of evidence to contradict answers to questions" },
    "154": { section: "154", title: "Court may recall and re-examine witness", description: "Court may recall and re-examine witness" },
    "155": { section: "155", title: "Refreshing memory", description: "Refreshing memory" },
    "157": { section: "157", title: "Previous statements of witness to prove consistency", description: "Previous statements of witness to prove consistency" },
    "158": { section: "158", title: "What court may inquire of witness", description: "What court may inquire of witness" },
    "159": { section: "159", title: "Cross-examination of witness called by court", description: "Cross-examination of witness called by court" },
    "160": { section: "160", title: "Evidence of witness as to facts in issue", description: "Evidence of witness as to facts in issue" },
    "161": { section: "161", title: "Witness to be examined on oath", description: "Witness to be examined on oath" },
    "162": { section: "162", title: "Proviso to section 161", description: "Proviso to section 161" },
    "163": { section: "163", title: "Right of adverse party as to writing used to refresh memory", description: "Right of adverse party as to writing used to refresh memory" },
    "164": { section: "164", title: "Expert may be called by court", description: "Expert may be called by court" },
    "165": { section: "165", title: "Judge's power to put questions", description: "Judge's power to put questions" },
    "166": { section: "166", title: "Power of jury or assessors", description: "Power of jury or assessors" },
  },
  "Negotiable Instruments Act": {
    "6": { section: "6", title: "Negotiable instrument defined", description: "Negotiable instrument defined" },
    "7": { section: "7", title: "Promissory note defined", description: "Promissory note defined" },
    "8": { section: "8", title: "Bill of exchange defined", description: "Bill of exchange defined" },
    "9": { section: "9", title: "Cheque defined", description: "Cheque defined" },
    "13": { section: "13", title: "Negotiable instrument", description: "Negotiable instrument" },
    "17": { section: "17", title: "Holder", description: "Holder" },
    "19": { section: "19", title: "Holder in due course", description: "Holder in due course" },
    "20": { section: "20", title: "Payment in due course", description: "Payment in due course" },
    "21": { section: "21", title: "Negotiation", description: "Negotiation" },
    "25": { section: "25", title: "Holder's right of recourse", description: "Holder's right of recourse" },
    "30": { section: "30", title: "Liability of drawer", description: "Liability of drawer" },
    "31": { section: "31", title: "Liability of drawee of bill", description: "Liability of drawee of bill" },
    "34": { section: "34", title: "Liability of acceptor", description: "Liability of acceptor of bill" },
    "35": { section: "35", title: "Liability of endorser", description: "Liability of endorser" },
    "36": { section: "36", title: "Liability of prior parties", description: "Liability of prior parties" },
    "37": { section: "37", title: "Liability of maker of note", description: "Liability of maker of note" },
    "38": { section: "38", title: "Liability of accommodation party", description: "Liability of accommodation party" },
    "42": { section: "42", title: "When notice of dishonour is necessary", description: "When notice of dishonour is necessary" },
    "43": { section: "43", title: "Time for notice of dishonour", description: "Time for notice of dishonour" },
    "44": { section: "44", title: "Mode of giving notice of dishonour", description: "Mode of giving notice of dishonour" },
    "45": { section: "45", title: "By whom notice may be given", description: "By whom notice may be given" },
    "46": { section: "46", title: "To whom notice may be given", description: "To whom notice may be given" },
    "47": { section: "47", title: "Notice of dishonour when agent cannot be found", description: "Notice of dishonour when agent cannot be found" },
    "48": { section: "48", title: "When notice need not be given", description: "When notice need not be given" },
    "50": { section: "50", title: "Mode of giving notice of dishonour", description: "Mode of giving notice of dishonour" },
    "52": { section: "52", title: "Notice of dishonour to drawer", description: "Notice of dishonour to drawer" },
    "53": { section: "53", title: "Notice of dishonour to endorser", description: "Notice of dishonour to endorser" },
    "54": { section: "54", title: "When notice need not be given to drawer", description: "When notice need not be given to drawer" },
    "55": { section: "55", title: "When notice need not be given to endorser", description: "When notice need not be given to endorser" },
    "56": { section: "56", title: "Notice of dishonour when party is dead", description: "Notice of dishonour when party is dead" },
    "57": { section: "57", title: "Notice of dishonour to agent of party", description: "Notice of dishonour to agent of party" },
    "58": { section: "58", title: "Effect of delay in giving notice", description: "Effect of delay in giving notice" },
    "59": { section: "59", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "60": { section: "60", title: "When notice need not be given", description: "When notice need not be given" },
    "61": { section: "61", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "62": { section: "62", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "63": { section: "63", title: "When notice need not be given", description: "When notice need not be given" },
    "64": { section: "64", title: "Notice of dishonour when party is dead", description: "Notice of dishonour when party is dead" },
    "65": { section: "65", title: "Notice of dishonour to agent of party", description: "Notice of dishonour to agent of party" },
    "66": { section: "66", title: "Effect of delay in giving notice", description: "Effect of delay in giving notice" },
    "67": { section: "67", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "68": { section: "68", title: "When notice need not be given", description: "When notice need not be given" },
    "69": { section: "69", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "70": { section: "70", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "71": { section: "71", title: "When notice need not be given", description: "When notice need not be given" },
    "72": { section: "72", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "73": { section: "73", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "74": { section: "74", title: "When notice need not be given", description: "When notice need not be given" },
    "75": { section: "75", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "76": { section: "76", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "77": { section: "77", title: "When notice need not be given", description: "When notice need not be given" },
    "78": { section: "78", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "79": { section: "79", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "80": { section: "80", title: "When notice need not be given", description: "When notice need not be given" },
    "81": { section: "81", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "82": { section: "82", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "83": { section: "83", title: "When notice need not be given", description: "When notice need not be given" },
    "84": { section: "84", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "85": { section: "85", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "86": { section: "86", title: "When notice need not be given", description: "When notice need not be given" },
    "87": { section: "87", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "88": { section: "88", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "89": { section: "89", title: "When notice need not be given", description: "When notice need not be given" },
    "90": { section: "90", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "91": { section: "91", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "92": { section: "92", title: "When notice need not be given", description: "When notice need not be given" },
    "93": { section: "93", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "94": { section: "94", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "95": { section: "95", title: "When notice need not be given", description: "When notice need not be given" },
    "96": { section: "96", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "97": { section: "97", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "98": { section: "98", title: "When notice need not be given", description: "When notice need not be given" },
    "99": { section: "99", title: "When notice is dispensed with", description: "When notice is dispensed with" },
    "100": { section: "100", title: "Effect of notice of dishonour", description: "Effect of notice of dishonour" },
    "138": { section: "138", title: "Dishonour of cheque for insufficiency of funds", description: "Dishonour of cheque for insufficiency of funds — criminal liability" },
  },
};

// Get all available act names
export function getAvailableActs(): string[] {
  return Object.keys(ACT_SECTIONS);
}

// Get sections for an act
export function getSectionsForAct(act: string): SectionInfo[] {
  const sections = ACT_SECTIONS[act];
  if (!sections) return [];
  return Object.values(sections);
}

// Search sections by query
export function searchSections(query: string): SectionInfo[] {
  const results: SectionInfo[] = [];
  const q = query.toLowerCase();

  for (const act of Object.values(ACT_SECTIONS)) {
    for (const section of Object.values(act)) {
      if (
        section.section.toLowerCase().includes(q) ||
        section.title.toLowerCase().includes(q) ||
        section.description.toLowerCase().includes(q)
      ) {
        results.push(section);
      }
    }
  }

  return results;
}

// Get section info
export function getSectionInfo(act: string, section: string): SectionInfo | null {
  const actSections = ACT_SECTIONS[act];
  if (!actSections) return null;
  return actSections[section] || null;
}
